<section class="person-profile">
    <div class="person-photoContainer">
        <img src="<?php echo BASE_URI; ?>/css/images/stab.gif" alt="Furious George" />
    </div>
    <div class="person-details">
        <header>
            <h1>Furious George</h1>
        </header>
    </div>
</section>
<section class="person-profile">
    <div class="person-photoContainer">
        <img src="<?php echo BASE_URI; ?>/css/images/karl_monkey.jpg" alt="Karl" />
    </div>
    <div class="person-details">
        <header>
            <h1>Karl</h1>
        </header>
    </div>
</section>
