<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<style type="text/css" media="screen">
		@import url("/skins/default/skin.css");
		@import url("<?php echo $BASE_URL; ?>/style.css");
	</style>
	<title>Exmployee Directory - City of Bloomington, Indian</title>
</head>
<body>
<div id="banner">
	<h1><a href="<?php echo $BASE_URL; ?>">Employee Directory</a></h1><h2>City of Bloomington, Indiana</h2>
</div>
