<div class="menuBar">
	<form method="get" action="search.php">
		<fieldset>
			<a href="<?php echo BASE_URL; ?>">Departments</a>
			<a href="<?php echo BASE_URL; ?>/mainNumbers.php">Main Numbers</a>
			<a href="<?php echo BASE_URL; ?>/searchForm.php">Advanced Search</a>

			<label>Last Name: <input name="lastname" id="lastname" tabindex="1" /></label>
			<button type="submit" class="search">Search</button>
		</fieldset>
	</form>
</div>
