<div class="navigation">
	<!--
	<div>
		<form method="get" action="search.php">
		<table>
		<tr><td><label for="lastname">Last</label></td>
			<td><input name="lastname" id="last" size="6" /></td></tr>
		<tr><td><label for="firstname">First</label></td>
			<td><input name="firstname" id="firstname" size="6" /></td></tr>
		<tr><td><label for="extension">Ext</label></td>
			<td><input name="extension" id="extension" size="6" /></td></tr>
		<tr><td colspan="2"><button type="submit" class="search" value="Search" /></td></tr>
		</table>
		</form>
	</div>
	-->

	<div><div class="titleBar">Departments</div>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Accounting">Accounting</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Administration">Administration</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Bloomington Transit">Bloomington Transit</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Blucher Poole">Blucher Poole</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=City Clerk">City Clerk</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Communication">Communication</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Community and Family Resources">Community and Family Resources</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Controller">Controller</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Council Office">Council Office</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Customer Services">Customer Services</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Detectives">Detectives</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Dillman">Dillman</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Dispatch">Dispatch</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Employee Services">Employee Services</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Engineering">Engineering</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Fire">Fire</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Fleet Maintenance">Fleet Maintenance</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=HAND">HAND</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=ITS">ITS</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Legal">Legal</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Mayor's Office">Mayor's Office</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Monroe">Monroe</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Parking Enforcement">Parking Enforcement</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Parks and Recreation">Parks and Recreation</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Planning">Planning</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Public Works">Public Works</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Purchasing">Purchasing</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Records">Records</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Risk Management">Risk Management</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=T&amp;D">T&amp;D</a>
		<a href="<?php echo $BASE_URL; ?>/viewDepartment.php?department=Uniformed Officers">Uniformed Officers</a>
	</div>

</div>